### PR TITLE
fix the multi_semicolon bug 

### PR DESCRIPTION
**Pull request by RickieL**
fix the issue #7

### CODE REVIEW

**Comment by denji** [comment]
Input data:
```nginx
error_log /var/log/nginx-err.log; # [comment1|comment2|comment3];
```

Output result
```nginx
error_log /var/log/nginx-err.log;
# [comment1|comment2|comment3];
```

**Comment by RickieL** [comment]
@denji  fixed the semicolon with hash comment situation. Please have a try.

**Comment by denji** [comment]
LGTM, thanks a lot!

**Comment by denji** [comment]
Patch multi_semicolon bug is also required https://github.com/1connect/nginx-config-formatter/pull/8/commits/106d75e2d8141a877f7f7697db267e77d51642dc

**Comment by RickieL** [comment]
fix issue #14 #15

**Comment by denji** [comment]
```nginx
sub_filter '{TEST}' "rewrite";
```

```nginx
sub_filter ' {
    TEST
}
' "rewrite";
```

**Comment by RickieL** [comment]
My pull request just handled curly braces `{ }` double quotation marks `" "` .

**Comment by denji** [comment]
https://github.com/1connect/nginx-config-formatter/pull/8/commits/1b1242404af5335a5baac8e906c8c24562e7df6c

```diff
--- a/nginx.conf
+++ b/nginx.conf
@@ -1,7 +1,10 @@
 http {
     server {
         location / {
-            sub_filter '{TEST}' "rewrite";
+            sub_filter ' {
+                TEST
+            }
+            ' "rewrite";
         }
     }
 }

```

**Comment by slomkowski** [comment]
@RickieL sorry for late reaction, I'll try to merge pull requests in following days.

**Pull request closed without merging**
